version: "3.8"
services:
  web:
    build: ./apps/web
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://api:5000
    depends_on:
      - api
  api:
    build: ./apps/api
    ports:
      - "5000:5000"
    volumes:
      - ./apps/api:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/eco_petcare
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
  admin:
    build: ./apps/admin-dashboard
    ports:
      - "5174:5174"
    volumes:
      - ./apps/admin-dashboard:/app
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
  redis:
    image: redis:7
    ports:
      - "6379:6379"