version: "3.8"
services:
  api:
    build: ./apps/api
    ports:
      - "5000:5000"
    env_file:
      - ./apps/api/.env.local
    command: npm start
  web:
    build: ./apps/web
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env.local
    command: npm start
  admin-dashboard:
    build: ./apps/admin-dashboard
    ports:
      - "5174:5174"
    command: npm start
