version: "3.8"
services:
  api:
    build: ./apps/api
    ports:
      - "5000:5000"
    env_file:
      - ./apps/api/.env.local
    volumes:
      - ./apps/api:/app
    command: npm run dev
  web:
    build: ./apps/web
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env.local
    volumes:
      - ./apps/web:/app
    command: npm run dev
  admin-dashboard:
    build: ./apps/admin-dashboard
    ports:
      - "5174:5174"
    volumes:
      - ./apps/admin-dashboard:/app
    command: npm run dev
